### PR TITLE
lndclient: use Features map instead the deprecated GlobalFeatures in the NodeUpdate

### PR DESCRIPTION
**Pull request by bhandras**
Note: first commit to be updated once LND master is tagged.

### CODE REVIEW

**Comment by guggero** [comment]
Should this be opened against the `lnd-12-0` branch if it requires lnd `v0.12.0`?

We came up with the following plan for handling `lnd` compatibility:
 - master is always backward compatible with the last major version (so currently `lnd v0.11.0`)
 - we create branches for all minor versions and future major versions (there are the branches `lnd-11-1` and `lnd-12-0`) and merge PRs to those branches, if the features **require** that version to work.
 - we rebase the branches if needed and use tags to track versions that we depend on in other projects
 
I'm not sure when exactly we should merge the branches back. Probably we could merge the `lnd-11-1` as soon as `lnd v0.12.0` is out of RC.

@carlaKC is that also how you remember our Keybase convo? Or did I remember something incorrectly?

**Comment by bhandras** [comment]
> Should this be opened against the `lnd-12-0` branch if it requires lnd `v0.12.0`?
> 
> We came up with the following plan for handling `lnd` compatibility:
> 
>     * master is always backward compatible with the last major version (so currently `lnd v0.11.0`)
> 
>     * we create branches for all minor versions and future major versions (there are the branches `lnd-11-1` and `lnd-12-0`) and merge PRs to those branches, if the features **require** that version to work.
> 
>     * we rebase the branches if needed and use tags to track versions that we depend on in other projects
> 
> 
> I'm not sure when exactly we should merge the branches back. Probably we could merge the `lnd-11-1` as soon as `lnd v0.12.0` is out of RC.
> 
> @carlaKC is that also how you remember our Keybase convo? Or did I remember something incorrectly?

SGTM, I'll reopen this against lnd-12-0 just wasn't aware of this.

**Comment by carlaKC** [comment]
> SGTM, I'll reopen this against lnd-12-0 just wasn't aware of this policy.

We should write it down somewhere, since it's only documented in a closed PR rn 😅 

Ran into this the other day and it turns out you don't actually need to close and reopen, you can [switch](https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/) base branch.

**Comment by guggero** [comment]
> Ran into this the other day and it turns out you don't actually need to close and reopen, you can switch base branch.

Oooooh, nice! TIL, thank you!

**Review by guggero — APPROVED** [review]
LGTM, pending the switch to the `lnd-12-0` branch.

**Pull request merged**
