### PR TITLE
mod: bump to final version of lnd v0.12.0

### PR DESCRIPTION
**Pull request by guggero**
This PR bumps the `lnd-12-0` branch to the final version of `lnd`.

#### Pull Request Checklist

- [X] PR is opened against correct version branch.
- [X] Version compatibility matrix in the README and minimal required version
      in `lnd_services.go` are updated.

### CODE REVIEW

**Review by carlaKC — APPROVED** [review]
🕺

**Comment by carlaKC** [comment]
When we merge the 0.12 branch into master, are we going to squash it down at all? Could be nice to have this commit first and get rid of all the intermediate mod bumps. Not sure what we did last time.

**Comment by guggero** [comment]
Yeah, we can do that, sure. We haven't yet merged any of the branches. Had a discussion about it recently with @bhandras and we decided to not yet merge but instead continue with the rebasing pattern.
Because once we merge, we can't add new functionality to our other projects without also increasing the minimum backward compatible version.

What's your opinion on this, @carlaKC? How many versions back should we try to keep backward compatible?

**Comment by carlaKC** [comment]
> instead continue with the rebasing pattern

Yeah that sounds good to me! There's still a lot of older APIs missing in `lndclient` so I'm definitely for allowing space to add those without bumping minimum version.

> How many versions back should we try to keep backward compatible?

This is a magic number, but maybe 2? We could also just see how the rebase burden goes and play it by ear.

**Review by bhandras — APPROVED** [review]

**Pull request merged**
