### PR TITLE
Add `CancelSet` flag for `HtlcModify` interface

### PR DESCRIPTION
**Pull request by GeorgeTsagk**
## Description

Threads throug the new `CancelSet` flag of the `HtlcModify` interface, which is introduced in the bumped lnd version

### CODE REVIEW

**Review by guggero — COMMENTED** [review]
LGTM pending merge of `lnd` PR.

**Review by ffranr — APPROVED** [review]

**Comment by guggero** [comment]
`lnd` can now be bumped to `615f3d63`.

**Comment by GeorgeTsagk** [comment]
Done :heavy_check_mark:

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Pull request merged**
